apiVersion: v2
name: helm-chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: node01
    condition: node01.enabled
    # repository: file://charts/node01
    # version: 0.1.0
  - name: python01
    condition: python01.enabled
    # condition: python01.enabled
    # repository: file://charts/python01
    # version: 0.1.0
  - name: gradle-sample-app
    condition: gradle-sample-app.enabled
    # repository: file://charts/gradle-sample-app
    # version: 0.1.0
