### Global Values if any ###
global: {}

### Sub Charts Specific Values ###
# node 
node01:
enabled: true
  image:
    repository: surakshaniveus/ms-node01
    tag: "03"
#python
python01:
enabled: true
  image:
    repository: surakshaniveus/ms-python01
    tag: "02"
#java
gradle-sample-app:
enabled: true
  image:
    repository: surakshaniveus/ms-java01
    tag: "02"